version: 1.0
os: linux
files:
  - source: /
    destination: /var/www/html/laravel
hooks:
  AfterInstall:
    - location: ./scripts/after-install.sh
      runas: ubuntu
  ApplicationStop:
    - location: ./scripts/stop_server.sh
      timeout: 120
      runas: ubuntu
  

