version: 1.0
os: linux
files:
  - source: ./applaravel/
    destination: /var/www/html/laravel
      hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
      # runas: root
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
      # runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: ubuntu
      # runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ubuntu
      # runas: root
  

