version: 1.0
os: linux
files:
  - source: /
    destination: /var/www/html/laravel/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      # runas: ubuntu
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
      # runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      # runas: ubuntu
      # runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      # runas: ubuntu
      # runas: root
  

