version: 1.0
os: linux
files:
  - source: ./applaravel
    destination: /var/www/html/laravel
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 120
      runas: ubuntu
    - location: scripts/start_server
      timeout: 120
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install
      timeout: 120
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 120
      runas: ubuntu
  

