#!/bin/bash

# Project directory on server for your project.
export WEB_DIR="/var/www/html"
# Your server user. Used to fix permission issue & install our project dependcies
export WEB_USER="root"


# Change directory to project.
cd $WEB_DIR

# change user owner to ubuntu & fix storage permission issues.
# sudo chown -r $WEB_USER:$WEB_USER
# sudo chown -R www-data storage
# sudo chmod -R 777
sudo chmod 777 -r storage

# install composer dependcies
# composer install --no-dev --no-progress --prefer-dist
sudo -u $WEB_USER composer install --no-dev --no-progress --prefer-dist

# load .env file from AWS Systems Manager
# ./devops/scripts/generate-env

# generate app key & run migrations
# php artisan key:generate
sudo -u $WEB_USER php artisan key:generate
# php artisan migrate --force --no-interaction
sudo -u $WEB_USER php artisan migrate --force --no-interaction