#!/bin/bash

export INSTALLER="apt"
export INSTALLER_GET="apt-get"
# export APACHE="httpd"
export APACHE="apache2"

sudo $INSTALLER update -y
# sudo apt dist-upgrade -y
sudo $INSTALLER install -y $APACHE
# sudo systemctl status apache2
# sudo $INSTALLER install software-properties-common
# sudo add-apt-repository ppa:ondrej/php
sudo $INSTALLER_GET install -y php8.1
# sudo php -v


# php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

# php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
# php composer-setup.php
# php -r "unlink('composer-setup.php');"
# sudo mv composer.phar /usr/local/bin/composer


